AlertSystem/Controllers/AlertController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AlertSystem.DataBase;
using AlertSystem.Models;

namespace AlertSystem.Controllers
{
    public class AlertController : Controller
    {
        // GET: Alert
        ITEIndiaEntities DB = new ITEIndiaEntities();
        public ActionResult Index(int page = 1, int pageSize = 10)
        {
            int totalItems = DB.Production_System_Name.Count(); // Example

            List<Production_System_Name> data = DB.Production_System_Name
                         .OrderBy(e => e.ID)
                         .Skip((page - 1) * pageSize)
                         .Take(pageSize)
                         .ToList();

            //List<ProductionSystemNameViewModel> viewModelList = data.Select(d => new ProductionSystemNameViewModel
            //{
            //    Id = d.ID,
            //    systemname = d.SystemNum
            //}).ToList();

            //PagedResult<ProductionSystemNameViewModel> model = new PagedResult<ProductionSystemNameViewModel>
            //{
            //    Items = viewModelList,
            //    PageNumber = page,
            //    PageSize = pageSize,
            //    TotalItems = totalItems
            //};
            return View();
        }
    }
}

AlertSystem/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" data-layout="horizontal" data-topbar="light" data-sidebar="dark" data-sidebar-size="lg">
<head>
    @Html.Partial("~/Views/Shared/_title_meta.cshtml")
    @RenderSection("styles", required: false)
    @Html.Partial("~/Views/Shared/_head_css.cshtml")
</head>
<body>
    <!-- Begin page -->
    <div id="layout-wrapper">
        @Html.Partial("~/Views/Shared/_menu.cshtml")

        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="main-content">

            <div class="page-content">
                <div class="">
                    @Html.Partial("~/Views/Shared/_page_title.cshtml")

                    @RenderBody()
                </div>
            </div>
            @Html.Partial("~/Views/Shared/_footer.cshtml")
        </div>

    </div>
    <!-- END layout-wrapper -->
    @Html.Partial("~/Views/Shared/_customizer.cshtml")

    @Html.Partial("~/Views/Shared/_vendor_scripts.cshtml")

    @RenderSection("scripts", required: false)
</body>
</html>

AlertSystem/Views/Shared/_footer.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>document.write(new Date().getFullYear())</script> © S.S. White Technologies
            </div>
        </div>
    </div>
</footer>

AlertSystem/Views/Shared/_head_css.cshtml
<!-- Layout config Js -->
<script src="~/assets/js/layout.js"></script>
<!-- Bootstrap Css -->
<link href="~/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<!-- Icons Css -->
<link href="~/assets/css/icons.min.css" rel="stylesheet" type="text/css" />
<!-- App Css-->
<link href="~/assets/css/app.min.css" rel="stylesheet" type="text/css" />
<!-- custom Css-->
<link href="~/assets/css/custom.min.css" rel="stylesheet" type="text/css" />

AlertSystem/Views/Shared/_menu.cshtml
@Html.Partial("~/Views/Shared/_topbar.cshtml")
@Html.Partial("~/Views/Shared/_sidebar.cshtml")

AlertSystem/Views/Shared/_page_title.cshtml
<!-- start page title -->
<div class="row">
    <div class="col-12">
        <div class="page-title-box d-sm-flex align-items-center justify-content-between">
            <h4 class="mb-sm-0">@ViewBag.ptitle</h4>

            <div class="page-title-right">
                <ol class="breadcrumb m-0">
                    <li class="breadcrumb-item"><a href="javascript: void(0);">@ViewBag.pagetitle</a></li>
                    <li class="breadcrumb-item active">@ViewBag.ptitle</li>
                </ol>
            </div>

        </div>
    </div>
</div>
<!-- end page title -->

AlertSystem/Views/Shared/_sidebar.cshtml
<!-- ========== App Menu ========== -->
<div class="app-menu navbar-menu">
    <!-- LOGO -->
    <div class="navbar-brand-box">
        <a href="@Url.Action("Index", "Home")" class="logo logo-dark">
            <span class="logo-sm">
                <img src="~/assets/images/sswnew.png" alt="" height="50">
            </span>
            <span class="logo-lg">
                <img src="~/assets/images/sswnew.png" alt="" height="45" />
                <label style="color:white">
                    S.S. White Technologies
                </label>
            </span>
        </a>
        <a href="@Url.Action("Index", "Home")" class="logo logo-light">
            <span class="logo-sm">
                <img src="~/assets/images/sswnew.png" alt="" height="50">
            </span>
            <span class="logo-lg">
                <img src="~/assets/images/sswnew.png" alt="" height="45" />
                <label style="color:white">
                    S.S. White Technologies
                </label>
            </span>
        </a>
        <button type="button" class="btn btn-sm p-0 fs-20 header-item float-end btn-vertical-sm-hover" id="vertical-hover">
            <i class="ri-record-circle-line"></i>
        </button>
    </div>

    <div id="scrollbar">
        <div class="container-fluid">

            <div id="two-column-menu">
            </div>
            <ul class="navbar-nav" id="navbar-nav">
                <li class="menu-title"><span data-key="t-menu">Menu</span></li>



                @*<li class="nav-item">
                        <a class="nav-link menu-link" href="#sidebarAdvanceUI" data-bs-toggle="collapse" role="button"
                           aria-expanded="false" aria-controls="sidebarAdvanceUI">
                            <i class="ri-stack-line"></i> <span data-key="t-advance-ui">Advance UI</span>
                            <span class="badge badge-pill bg-success" data-key="t-new">New</span>
                        </a>
                        <div class="collapse menu-dropdown" id="sidebarAdvanceUI">
                            <ul class="nav nav-sm flex-column">
                                <li class="nav-item">
                                    <a href="@Url.Action("SweetAlerts", "AdvanceUI")" class="nav-link" data-key="t-sweet-alerts">Sweet Alerts</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("NestableList", "AdvanceUI")" class="nav-link" data-key="t-nestable-list">Nestable List</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Scrollbar", "AdvanceUI")" class="nav-link" data-key="t-scrollbar">Scrollbar</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Animation", "AdvanceUI")" class="nav-link" data-key="t-animation">Animation</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Tour", "AdvanceUI")" class="nav-link" data-key="t-tour">Tour</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("SwiperSlider", "AdvanceUI")" class="nav-link" data-key="t-swiper-slider">Swiper Slider</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Ratings", "AdvanceUI")" class="nav-link" data-key="t-ratings">Ratings</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("Highlight", "AdvanceUI")" class="nav-link" data-key="t-highlight">Highlight</a>
                                </li>
                                <li class="nav-item">
                                    <a href="@Url.Action("ScrollSpy", "AdvanceUI")" class="nav-link" data-key="t-scrollSpy">ScrollSpy</a>
                                </li>
                            </ul>
                        </div>
                    </li>*@

                <li class="nav-item">
                    <a class="nav-link menu-link" href="@Url.Action("Index", "Home")">
                        <i class="ri-honour-line"></i> <span data-key="t-widgets">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link menu-link" href="@Url.Action("Index", "Alert")">
                        <i class="ri-honour-line"></i> <span data-key="t-widgets">Test</span>
                    </a>
                </li>
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
    <div class="sidebar-background"></div>
</div>
<div class="vertical-overlay"></div>

AlertSystem/Views/Shared/_title_meta.cshtml
<meta charset="utf-8" />
<title>@ViewBag.title | Alert System</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta content="Premium Multipurpose Admin & Dashboard Template" name="description" />
<meta content="Themesbrand" name="author" />
<!-- App favicon -->
@*<link rel="shortcut icon" href="~/assets/images/favicon.ico">*@

AlertSystem/Views/Shared/_vendor_scripts.cshtml
<!-- JAVASCRIPT -->
<script src="~/assets/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/assets/js/Jquery.js"></script>
<script src="~/assets/libs/simplebar/simplebar.min.js"></script>
<script src="~/assets/libs/node-waves/waves.min.js"></script>
<script src="~/assets/libs/feather-icons/feather.min.js"></script>
<script src="~/assets/js/pages/plugins/lord-icon-2.1.0.js"></script>
<script src="~/assets/js/plugins.js"></script>